services:
  hv-travel-web:
    image: hv-travel-web
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5028:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - HVTravelDatabase__ConnectionString=${HVTravelDatabase__ConnectionString}
      - HVTravelDatabase__DatabaseName=HV-Travel

  mongodb:
    image: mongo:latest
    restart: "no"
    profiles:
      - local-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${LOCAL_TUNNEL_TOKEN}
    restart: "no"
    environment:
      - TUNNEL_TOKEN=${LOCAL_TUNNEL_TOKEN} # Token will be read from .env file
    depends_on:
      - hv-travel-web

volumes:
  mongo_data:
